### PR TITLE
Backgrounds and gradients

### PR DESCRIPTION
**Pull request by phylischumba**
This is a project clone of the apple.com page. It mainly focuses on backgrounds, gradients, and positions in HTML and CSS.
It contains a sticky navbar, the body with images, a background image, and a footer.
Various ways have been used to position the elements in their place.

### CODE REVIEW

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes 🔴
Hi @Phylis05, wow!! your project looks beautiful and it looks exactly as the original 👍 Beautiful effort 🙂 
There are a few comments to address before we can approve this beauty 😄This project is base on using background-image, background-url and background-gradients,  Find comments below:
- Let us fix the nav, let us apply background-gradient to the nav. Let us watch closely at the nav of the original page and try to make it look like it. Let us apply 2 different colors to the background-gradient
- Let us this section => ```<section class="lower-section">``` . Let us replace each of the `````` with ```<div>``` , give it a class and apply the ```background-image``` property to it. Let us remember to wrap the ```<div>``` with ```<a>``` . Example => ```<a><div class="myClass"></div></a>``` So that we can make them clickable. 
YEAH
- Let us remove the text on the main background
yh
- We can improve the README file by using this [template](https://github.com/microverseinc/readme-template)

Kindly make these changes and submit another code review 👍 
_Happy coding_ 👩‍💻 
@slack on **Daniel Larbi Addo**

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @Phylis05 
### Good job so far and for making the required changes from the previous review :clap: However, you still have some issues to solve before your project could be approved.
- Remove the horizontal scroll bar
- Remove the commented out code in html
comment

### Make these changes and resubmit for another code review. Good luck.
- Happy coding!

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Under Review By Tolulope Olusakin(TSE)
Please check on this in a few minutes for some feedback! :+1:

**Comment by nikasulo** [comment]
# Great work @Phylis05 ! :rocket: 
You REALLY pulled this off! :clap: There is just that one issue with the horizontal scroll. I left a comment with a hint I hope will be helpful to you in making this right, please make the necessary changes and request another review! I wish you the best and see you at the very top :rocket: 

#### Horizontal Scroll
You seem to have a little bug with one of the elements of the page, shooting out beyond the browser's maximum width. This may be as a result of a margin or padding you have set up. One of the easiest ways I have found to correct this issue is to set the default `box-sizing` property to `border-box` as follows `*{box-sizing: border-box}`. Please read some more about it [here](https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing).

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Review by nikasulo — APPROVED** [review]
# Congratulations @Phylis05 :medal_military: 
You may merge and move forward! I wish you the very best in all you endeavors and see you at the top :rocket: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Pull request merged**
